export const moviesData = {
  results: [
    {
      Actors: 'Chris Pratt, Zoe Saldana, Dave Bautista',
      Country: 'United States',
      Director: 'James Gunn',
      Genre: 'Action, Adventure, Comedy',
      Language: 'English',
      Plot: "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.",
      Poster:
        'https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg',
      Rated: 'PG-13',
      Released: '05 May 2017',
      Runtime: '136 min',
      Title: 'Guardians of the Galaxy Vol. 2',
      Type: 'movie',
      Writer: 'James Gunn, Dan Abnett, Andy Lanning',
      Year: '2017',
      imdbRating: '7.6',
    },
    {
      Title: 'Jonah: A VeggieTales Movie',
      Year: '2002',
      Released: '04 Oct 2002',
      Genre: 'Animation, Adventure, Comedy',
      Director: 'Phil Vischer, Mike Nawrocki',
      Writer: 'Phil Vischer, Mike Nawrocki, Tim Hodge',
      Actors: 'Phil Vischer, Mike Nawrocki, Tim Hodge',
      Plot: 'When the singing Veggies encounter some car trouble, they are stranded at an old rundown seafood joint, where nothing is quite as it seems.',
      Language: 'English',
      Country: 'United States',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMjA0OTk5MTk0M15BMl5BanBnXkFtZTYwNTgxMDg5._V1_SX300.jpg',

      imdbRating: '6.4',
      Type: 'movie',
    },
    {
      Title: 'Super Girl',
      Released: '27 Aug 2014',
      Runtime: '16 min',
      Genre: 'Short, Adventure, Drama',
      Director: 'Vaani Arora, Hemant Gaba',
      Writer: 'Vaani Arora',
      Actors: 'Andrew Hoffland, Mellanie Hubert, Nandan Jha',
      Plot: 'Nadia loves superheroes like any other kid her age, but unlike others, she really believes that she can be one.',
      Language: 'English',
      Country: 'India',
      Awards: 'N/A',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BYzEwMjNiNzgtZGIwYS00NDE4LTk0OGEtZGVhOTU5NDRjYzBkXkEyXkFqcGdeQXVyMzA1NDA3NDA@._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '5.7/10'}],
      Metascore: 'N/A',
      imdbRating: '5.7',
      imdbVotes: '23',
      imdbID: 'tt4116872',
      Type: 'movie',
    },
    {
      Title: 'Mountain Men',
      Year: '2014',
      Rated: 'Not Rated',
      Released: '29 Jan 2016',

      Genre: 'Comedy, Drama',
      Director: 'Cameron Labine',
      Writer: 'Cameron Labine, Elan Mastai',
      Actors: 'Chace Crawford, Tyler Labine, Christine Willes',
      Plot: 'Mountain Men is a comedy/drama that follows two estranged brothers, Toph and Cooper, as they journey to a remote family cabin in the mountains to evict a squatter. Buried resentment and bruised egos soon derail the plan and when t...',
      Language: 'English',
      Country: 'Canada',

      Poster:
        'https://m.media-amazon.com/images/M/MV5BMjM5NDM1NTIzMF5BMl5BanBnXkFtZTgwMjY4NDg0NzE@._V1_SX300.jpg',

      imdbRating: '5.9',

      imdbID: 'tt3529664',
      Type: 'movie',
    },
    {
      Title: 'Well-Intended Love 2',
      Year: '2020',
      Rated: 'N/A',
      Released: 'N/A',
      Runtime: 'N/A',
      Genre: 'Drama, Romance',
      Director: 'Qiang Wu',
      Writer: 'N/A',
      Actors: 'Xu Kai Cheng, Wang Shuang, Ian Yi, Huang Qian Shuo',
      Plot: "Xia Lin (Wang Shuang) and her overbearing CEO husband Ling Yi Zhou (Xu Kai Cheng) are enjoying their married life with their little son, but what will happen once Yi Zhou's ex-classmate ...",
      Language: 'Mandarin',
      Country: 'China',
      Awards: 'N/A',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BYzNkN2UyYmQtYWI5NS00ODI4LTk5OTUtODVkZTUxOTkyZjk4XkEyXkFqcGdeQXVyMjQ0OTYxOTc@._V1_SX300.jpg',
      Ratings: [],

      imdbID: 'tt10825084',
      Type: 'movie',
    },
    {
      Title: 'Taqdeer',
      Year: '1983',
      Rated: 'N/A',
      Released: '04 Feb 1983',
      Runtime: '125 min',
      Genre: 'Action, Drama, Romance',
      Director: 'Brij',
      Writer: 'Madan Joshi, Suhrid Kar, K.K. Shukla',
      Actors: 'Mithun Chakraborty, Zeenat Aman, Hema Malini',
      Plot: "Widower Pratap Singh lives a wealthy lifestyle along with two married sons, Randhir and Ranvir. While Ranvir's wife continues to be childless, Randhir has a daughter, and his wife is expecting a second child. Pratap wants Randhir ...",
      Language: 'Hindi',
      Country: 'India',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BZmRiNGY0YjktNDc1Yy00ZjQ1LThiMTgtOGNlNDEzMmIyYTc0L2ltYWdlXkEyXkFqcGdeQXVyNTEwOTgzNzI@._V1_SX300.jpg',

      imdbRating: '5.8',

      imdbID: 'tt0158259',
      Type: 'movie',
    },
    {
      Title: '12th Fail',
      Year: '2023',
      Rated: 'N/A',
      Released: '27 Oct 2023',
      Runtime: '147 min',
      Genre: 'Biography, Drama',
      Director: 'Vidhu Vinod Chopra',
      Writer: 'Vidhu Vinod Chopra, Jaskunwar Kohli, Anurag Pathak',
      Actors: 'Vikrant Massey, Medha Shankar, Joshi Anantvijay',
      Plot: 'The real-life story of IPS Officer Manoj Kumar Sharma and IRS Officer Shraddha Joshi.',
      Language: 'Hindi, Malayalam, Tamil, Telugu, Kannada',
      Country: 'India',
      Awards: '9 wins & 11 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BOTJlY2U2ZmYtMzU3Ny00ZDI3LWEwMDYtOWIxNzdhZDI5ZWRkXkEyXkFqcGdeQXVyMTY3ODkyNDkz._V1_SX300.jpg',
      imdbRating: '9.1',

      imdbID: 'tt23849204',
      Type: 'movie',
    },
    {
      Title: 'Ramayana: The Legend of Prince Rama',
      Year: '1993',
      Rated: 'PG',
      Released: '03 Nov 1997',
      Runtime: '135 min',
      Genre: 'Animation, Action, Adventure',
      Director: 'Ram Mohan, Yûgô Sakô, Koichi Saski',
      Writer: 'Rani Burra, Ram Mohan, Yûgô Sakô',
      Actors: 'Arun Govil, Nikhil Kapoor, Edie Mirman',
      Plot: 'An anime adaptation of the Hindu epic the Ramayana, where Lord Ram combats the wicked king Ravana.',
      Language: 'Hindi, English',
      Country: 'India, Japan',
      Awards: '1 win',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BNTJjZTViZTEtNGVhNy00ODlmLTg2YTEtZDQ4NzBiNGMzMGJkXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '9.2/10'}],
      Metascore: 'N/A',
      imdbRating: '9.2',
      imdbVotes: '13,574',
      imdbID: 'tt0259534',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Nayakan',
      Year: '1987',
      Rated: 'Not Rated',
      Released: '21 Oct 1987',
      Runtime: '145 min',
      Genre: 'Crime, Drama',
      Director: 'Mani Ratnam',
      Writer: 'Balakumaran, Rajasri, Mani Ratnam',
      Actors: 'Kamal Haasan, Saranya Ponvannan, Delhi Ganesh',
      Plot: "A common man's struggles against a corrupt police force put him on the wrong side of the law. He becomes a don, who is loved and respected by many, but his growing power and influence exact a heavy toll.",
      Language: 'Tamil',
      Country: 'India',
      Awards: '6 wins & 1 nomination',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BNzEyZTFmZTItYWU2My00ZWZkLTg2NWMtMTEwYmM5YzFmNzFhXkEyXkFqcGdeQXVyMTA0MTM5NjI2._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '8.6/10'}],
      Metascore: 'N/A',
      imdbRating: '8.6',
      imdbVotes: '22,823',
      imdbID: 'tt0093603',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: '3 Idiots',
      Year: '2009',
      Rated: 'PG-13',
      Released: '25 Dec 2009',
      Runtime: '170 min',
      Genre: 'Comedy, Drama',
      Director: 'Rajkumar Hirani',
      Writer: 'Abhijat Joshi, Rajkumar Hirani, Vidhu Vinod Chopra',
      Actors: 'Aamir Khan, Madhavan, Mona Singh',
      Plot: 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them "idiots".',
      Language: 'Hindi, English',
      Country: 'India',
      Awards: '64 wins & 30 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
      Ratings: [
        {Source: 'Internet Movie Database', Value: '8.4/10'},
        {Source: 'Rotten Tomatoes', Value: '100%'},
        {Source: 'Metacritic', Value: '67/100'},
      ],
      Metascore: '67',
      imdbRating: '8.4',
      imdbVotes: '429,262',
      imdbID: 'tt1187043',
      Type: 'movie',
      DVD: '29 Nov 2016',
      BoxOffice: '$6,532,874',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Crew',
      Year: '2012–',
      Rated: 'N/A',
      Released: '20 Jun 2012',
      Runtime: '120 min',
      Genre: 'Drama',
      Director: 'N/A',
      Writer: 'N/A',
      Actors: 'Ezie Cotler, Stephen Medvidick, Chris Ferretti',
      Plot: 'Three young men, errand boys for a ruthless NYC mafia boss. Hatch a plan to steal from the boss and use that money to start their own Crew.',
      Language: 'English',
      Country: 'United States',
      Awards: 'N/A',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMjEzMDU2NDMxMF5BMl5BanBnXkFtZTcwMTc3MzQ0OA@@._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '7.3/10'}],
      Metascore: 'N/A',
      imdbRating: '7.3',
      imdbVotes: '7',
      imdbID: 'tt2370640',
      Type: 'series',
      totalSeasons: '3',
      Response: 'True',
    },
    {
      Title: 'Mirzapur',
      Year: '2018–',
      Rated: 'TV-MA',
      Released: '15 Nov 2018',
      Runtime: '60 min',
      Genre: 'Action, Crime, Drama',
      Director: 'N/A',
      Writer: 'Puneet Krishna, Karan Anshuman',
      Actors: 'Pankaj Tripathi, Ali Fazal, Divyendu Sharma',
      Plot: 'A shocking incident at a wedding procession ignites a series of events entangling the lives of two families in the lawless city of Mirzapur.',
      Language: 'Hindi',
      Country: 'India',
      Awards: '9 wins & 41 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BN2NlNGYwYTUtMTczMi00NGVjLTgwMzUtNjBkZjIyNDc2NjcxXkEyXkFqcGdeQXVyODQ5NDUwMDk@._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '8.5/10'}],
      Metascore: 'N/A',
      imdbRating: '8.5',
      imdbVotes: '81,031',
      imdbID: 'tt6473300',
      Type: 'series',
      totalSeasons: '3',
      Response: 'True',
    },
    {
      Title: 'RRR',
      Year: '2022',
      Rated: 'Not Rated',
      Released: '25 Mar 2022',
      Runtime: '187 min',
      Genre: 'Action, Drama',
      Director: 'S.S. Rajamouli',
      Writer: 'Vijayendra Prasad, S.S. Rajamouli, Sai Madhav Burra',
      Actors: 'N.T. Rama Rao Jr., Ram Charan, Ajay Devgn',
      Plot: 'A fearless warrior on a perilous mission comes face to face with a steely cop serving British forces in this epic saga set in pre-independent India.',
      Language:
        'Hindi, Malayalam, Portuguese, Tamil, Kannada, Korean, Turkish, Spanish, Telugu, English',
      Country: 'India',
      Awards: 'Won 1 Oscar. 83 wins & 150 nominations total',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BODUwNDNjYzctODUxNy00ZTA2LWIyYTEtMDc5Y2E5ZjBmNTMzXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
      Ratings: [
        {Source: 'Internet Movie Database', Value: '7.8/10'},
        {Source: 'Rotten Tomatoes', Value: '95%'},
        {Source: 'Metacritic', Value: '83/100'},
      ],
      Metascore: '83',
      imdbRating: '7.8',
      imdbVotes: '165,437',
      imdbID: 'tt8178634',
      Type: 'movie',
      DVD: '22 May 2022',
      BoxOffice: '$15,156,051',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },

    {
      Title: 'Barbie',
      Year: '2023',
      Rated: 'PG-13',
      Released: '21 Jul 2023',
      Runtime: '114 min',
      Genre: 'Adventure, Comedy, Fantasy',
      Director: 'Greta Gerwig',
      Writer: 'Greta Gerwig, Noah Baumbach',
      Actors: 'Margot Robbie, Ryan Gosling, Issa Rae',
      Plot: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
      Language: 'English, Spanish',
      Country: 'United States, United Kingdom',
      Awards: 'Nominated for 8 Oscars. 159 wins & 417 nominations total',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
      Ratings: [
        {Source: 'Internet Movie Database', Value: '6.9/10'},
        {Source: 'Rotten Tomatoes', Value: '88%'},
        {Source: 'Metacritic', Value: '80/100'},
      ],
      Metascore: '80',
      imdbRating: '6.9',
      imdbVotes: '495,309',
      imdbID: 'tt1517268',
      Type: 'movie',
      DVD: '12 Sep 2023',
      BoxOffice: '$636,238,421',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Jersey',
      Year: '2019',
      Rated: 'Not Rated',
      Released: '19 Apr 2019',
      Runtime: '157 min',
      Genre: 'Drama, Sport',
      Director: 'Gowtam Tinnanuri',
      Writer: 'Gowtam Tinnanuri',
      Actors: 'Nani, Shraddha Srinath, Sathyaraj',
      Plot: "A failed cricketer decides to revive his cricketing career in his late 30's despite everyone being skeptical of his ability to do so.",
      Language: 'Telugu, Hindi',
      Country: 'India',
      Awards: '9 wins & 7 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BYjc0MWFiYTMtNmYyOS00ODczLWEyMzItNzI4YjY0YjJjZGVjXkEyXkFqcGdeQXVyNzEwNjg3MjE@._V1_SX300.jpg',
      Ratings: [
        {Source: 'Internet Movie Database', Value: '8.5/10'},
        {Source: 'Rotten Tomatoes', Value: '63%'},
      ],
      Metascore: 'N/A',
      imdbRating: '8.5',
      imdbVotes: '21,963',
      imdbID: 'tt8948790',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Sunflower',
      Year: '2021–',
      Rated: 'N/A',
      Released: '11 Jun 2021',
      Runtime: 'N/A',
      Genre: 'Comedy, Crime',
      Director: 'N/A',
      Writer: 'Vikas Bahl',
      Actors: 'Sunil Grover, Ashish Vidyarthi, Ranvir Shorey',
      Plot: 'A quirky murder mystery based in a housing society called Sunflower. Its simpleton resident Sonu dives headlong into a murder mystery and becomes the chief suspect. What happens next?',
      Language: 'Hindi, Tamil, Telugu',
      Country: 'India',
      Awards: '3 wins & 4 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BYWZhZDA5MTQtZGIyMC00NmE3LTkxZWMtNjI2YTlhYjI4YmM2XkEyXkFqcGdeQXVyMTIzMzg0MTM2._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '7.3/10'}],
      Metascore: 'N/A',
      imdbRating: '7.3',
      imdbVotes: '10,676',
      imdbID: 'tt13304410',
      Type: 'series',
      totalSeasons: '1',
      Response: 'True',
    },
    {
      Title: 'The Family Man',
      Year: '2019–',
      Rated: 'TV-MA',
      Released: '19 Sep 2019',
      Runtime: '2 min',
      Genre: 'Action, Comedy, Drama',
      Director: 'N/A',
      Writer: 'Krishna D.K., Raj Nidimoru',
      Actors: 'Manoj Bajpayee, Samantha Ruth Prabhu, Priyamani',
      Plot: 'A working man from the National Investigation Agency tries to protect the nation from terrorism, but he also needs to keep his family safe from his secret job.',
      Language: 'Arabic, English, Tamil, Hindi',
      Country: 'India',
      Awards: '56 wins & 46 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMzRjZWVmMzItNTdmYS00OWEzLTgyOGUtNThiNTU2ZThlYjY0XkEyXkFqcGdeQXVyMTIxMDk2NDE4._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '8.7/10'}],
      Metascore: 'N/A',
      imdbRating: '8.7',
      imdbVotes: '97,400',
      imdbID: 'tt9544034',
      Type: 'series',
      totalSeasons: '2',
      Response: 'True',
    },
    {
      Title: 'Sita Ramam',
      Year: '2022',
      Rated: 'N/A',
      Released: '05 Aug 2022',
      Runtime: '163 min',
      Genre: 'Action, Drama, Mystery',
      Director: 'Hanu Raghavapudi',
      Writer: 'Hanu Raghavapudi, Jay Krishna, Raj Kumar Kandamudi',
      Actors: 'Dulquer Salmaan, Mrunal Thakur, Rashmika Mandanna',
      Plot: "An orphan soldier, Lieutenant Ram's life changes, after he gets a letter from a girl named Sita. He meets her and love blossoms between them. When he comes back to his camp in Kashmir,After he gets caught in jail, he sends a lette...",
      Language: 'Telugu',
      Country: 'India',
      Awards: '6 wins & 12 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BN2RjZDJhYzUtOTQ5Yy00OWM3LWE5OTctM2Y0YWVmNzAzODllXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_SX300.jpg',
      Ratings: [
        {Source: 'Internet Movie Database', Value: '8.6/10'},
        {Source: 'Rotten Tomatoes', Value: '86%'},
      ],
      Metascore: 'N/A',
      imdbRating: '8.6',
      imdbVotes: '66,973',
      imdbID: 'tt20850406',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Sacred Games',
      Year: '2018–2019',
      Rated: 'TV-MA',
      Released: '06 Jul 2018',
      Runtime: '1 min',
      Genre: 'Action, Crime, Drama',
      Director: 'N/A',
      Writer: 'Varun Grover',
      Actors: 'Saif Ali Khan, Nawazuddin Siddiqui, Neeraj Kabi',
      Plot: 'A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.',
      Language: 'Hindi',
      Country: 'India, United States',
      Awards: '15 wins & 17 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMjJlMjJlMzYtNmU5Yy00N2MwLWJmMjEtNWUwZWIyMGViZDgyXkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '8.5/10'}],
      Metascore: 'N/A',
      imdbRating: '8.5',
      imdbVotes: '92,343',
      imdbID: 'tt6077448',
      Type: 'series',
      totalSeasons: '2',
      Response: 'True',
    },
    {
      Title: 'Kota Factory',
      Year: '2019–2021',
      Rated: 'TV-14',
      Released: '28 Aug 2021',
      Runtime: '45 min',
      Genre: 'Comedy, Drama',
      Director: 'N/A',
      Writer: 'Saurabh Khanna',
      Actors: 'Mayur More, Jitendra Kumar, Ranjan Raj',
      Plot: "Dedicated to Shrimati SL Loney ji, Shri Irodov ji and Maanniya HC Verma ji, 'Kota Factory' is TVF's latest original. India's first 'Black and White' show highlights the problems present day IIT-JEE aspirants face in their day-to-d...",
      Language: 'Hindi',
      Country: 'India',
      Awards: '9 wins & 15 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BOGVmMGYwZTEtOGFlYS00ODRhLTg3M2MtMzc1OGNhNzU3N2IzXkEyXkFqcGdeQXVyNDY4NjAxNTc@._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '9.0/10'}],
      Metascore: 'N/A',
      imdbRating: '9.0',
      imdbVotes: '78,815',
      imdbID: 'tt9432978',
      Type: 'series',
      totalSeasons: '2',
      Response: 'True',
    },
    {
      Title: 'R U Faster Than a Redneck?',
      Year: '2013–',
      Rated: 'N/A',
      Released: '22 Feb 2013',
      Runtime: '30 min',
      Genre: 'Reality-TV',
      Director: 'N/A',
      Writer: 'N/A',
      Actors: 'Jon Reep, Nick DeKay, Ken Squier',
      Plot: 'Racing against rednecks. That is it.',
      Language: 'English',
      Country: 'United States',
      Awards: 'N/A',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMDg0MThlMjktMzY1Mi00MmNhLTkzM2ItNzA2NTk3MWM2MzdjXkEyXkFqcGdeQXVyMTAwMzM3NDI3._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '6.9/10'}],
      Metascore: 'N/A',
      imdbRating: '6.9',
      imdbVotes: '87',
      imdbID: 'tt2711726',
      Type: 'series',
      totalSeasons: '1',
      Response: 'True',
    },
    {
      Title: 'Maharani',
      Year: '2021–',
      Rated: 'N/A',
      Released: '28 May 2021',
      Runtime: 'N/A',
      Genre: 'Drama',
      Director: 'N/A',
      Writer: 'Subhash Kapoor',
      Actors: 'Huma Qureshi, Uday Atroliya, Sohum Shah',
      Plot: "CM Rani Bharti is accused of misgovernance and 'jungle raj' in the state. With the crumbling political scenario and constant opposition, will she succeed in this game of power?",
      Language: 'Hindi',
      Country: 'India',
      Awards: '8 wins & 22 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BZjBkZTZjMzQtZDJhMS00MzE3LTg0MDctZjZhZDhhYjFlODZjXkEyXkFqcGdeQXVyOTIxMzQ0NzU@._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '7.9/10'}],
      Metascore: 'N/A',
      imdbRating: '7.9',
      imdbVotes: '8,748',
      imdbID: 'tt14420552',
      Type: 'series',
      totalSeasons: '2',
      Response: 'True',
    },
    {
      Title: 'Dunki',
      Year: '2023',
      Rated: 'N/A',
      Released: '21 Dec 2023',
      Runtime: '160 min',
      Genre: 'Comedy, Drama',
      Director: 'Rajkumar Hirani',
      Writer: 'Abhijat Joshi, Rajkumar Hirani, Kanika Dhillon',
      Actors: 'Taapsee Pannu, Ryan Cretney, Priya Sindher',
      Plot: 'When his friends in Punjab struggle to clear the immigration process, an ex-soldier guides them on a risky journey to enter the UK without permission.',
      Language: 'Hindi',
      Country: 'India',
      Awards: '2 wins & 18 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMzQ0NDRhNmItYzllYS00NDdlLTk0YTctZDQ5YmFkYjdkNDcyXkEyXkFqcGdeQXVyNTYwMzA0MTM@._V1_SX300.jpg',
      Ratings: [
        {Source: 'Internet Movie Database', Value: '6.8/10'},
        {Source: 'Rotten Tomatoes', Value: '50%'},
      ],
      Metascore: 'N/A',
      imdbRating: '6.8',
      imdbVotes: '69,310',
      imdbID: 'tt15428134',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: '$7,460,159',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Animal',
      Year: '2023',
      Rated: 'Not Rated',
      Released: '01 Dec 2023',
      Runtime: '204 min',
      Genre: 'Action, Crime, Drama',
      Director: 'Sandeep Reddy Vanga',
      Writer: 'Suresh Bandaru, Saurabh Gupta, Pranay Reddy Vanga',
      Actors: 'Ranbir Kapoor, Anil Kapoor, Bobby Deol',
      Plot: "The hardened son of a powerful industrialist returns home after years abroad and vows to take bloody revenge on those threatening his father's life.",
      Language: 'Hindi',
      Country: 'India',
      Awards: '8 wins & 21 nominations',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BNGViM2M4NmUtMmNkNy00MTQ5LTk5MDYtNmNhODAzODkwOTJlXkEyXkFqcGdeQXVyMTY1NDY4NTIw._V1_SX300.jpg',
      Ratings: [{Source: 'Internet Movie Database', Value: '6.3/10'}],
      Metascore: 'N/A',
      imdbRating: '6.3',
      imdbVotes: '81,177',
      imdbID: 'tt13751694',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: '$15,004,482',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Stree 2',
      Year: '2024',
      Rated: 'N/A',
      Released: '30 Aug 2024',
      Runtime: 'N/A',
      Genre: 'Comedy, Horror',
      Director: 'Amar Kaushik',
      Writer: 'Niren Bhatt',
      Actors: 'Pankaj Tripathi, Tamannaah Bhatia, Rajkummar Rao',
      Plot: 'The story of a witch who captures men in the middle of the night when they are alone and abandons them with only their clothes.',
      Language: 'Hindi',
      Country: 'India',
      Awards: 'N/A',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BMDRhM2QyMGQtM2RiNi00OWYyLTlkZjktOTUyNjU0NDUyYmMyXkEyXkFqcGdeQXVyMTczNDc1NjI2._V1_SX300.jpg',
      Ratings: [],
      Metascore: 'N/A',
      imdbRating: 'N/A',
      imdbVotes: 'N/A',
      imdbID: 'tt27510174',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Singham Again',
      Year: '2024',
      Rated: 'N/A',
      Released: '15 Aug 2024',
      Runtime: 'N/A',
      Genre: 'Action, Drama',
      Director: 'Rohit Shetty',
      Writer: 'Muhammad Asif Ali, Abhijeet Khuman, Kshitij Patwardhan',
      Actors: 'Ajay Devgn, Kareena Kapoor, Deepika Padukone',
      Plot: 'Plot under wraps.',
      Language: 'Hindi',
      Country: 'India',
      Awards: 'N/A',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BYmY3MGM0ZDMtYWZiYS00MDM2LWI5YjUtZDk4YzBjMTAwZGZlXkEyXkFqcGdeQXVyOTE2NDU1NDM@._V1_SX300.jpg',
      Ratings: [],
      Metascore: 'N/A',
      imdbRating: 'N/A',
      imdbVotes: 'N/A',
      imdbID: 'tt11976134',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Bastar: The Naxal Story',
      Year: '2024',
      Rated: 'N/A',
      Released: '05 Apr 2024',
      Runtime: 'N/A',
      Genre: 'Crime, Drama',
      Director: 'Sudipto Sen',
      Writer: 'Amarnath Jha, Sudipto Sen',
      Actors: 'Adah Sharma, Anupam Joardar',
      Plot: 'Follows a group of Kerala women who have been forced to convert to Islam and join the Islamic State of Iraq and Syria (ISIS).',
      Language: 'Hindi',
      Country: 'India',
      Awards: 'N/A',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BZTJlYWRiNWMtZDg0My00N2VhLWIzMGEtOGZlMTEyYWY1OWVlXkEyXkFqcGdeQXVyMTQ3Mzk2MDg4._V1_SX300.jpg',
      Ratings: [],
      Metascore: 'N/A',
      imdbRating: 'N/A',
      imdbVotes: 'N/A',
      imdbID: 'tt28221135',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
    {
      Title: 'Do Aur Do Pyaar',
      Year: '2024',
      Rated: 'N/A',
      Released: '29 Mar 2024',
      Runtime: 'N/A',
      Genre: 'Drama',
      Director: 'Shirsha Guha Thakurta',
      Writer: 'Amrita Bagchi, Eisha Chopra, Suprotim Sengupta',
      Actors: "Vidya Balan, Pratik Gandhi, Ileana D'Cruz",
      Plot: "A couple on the brink of a breakup are cheating on each other with two sexy outsiders. Whilst they're waiting to reveal their secret and go their separate ways, life has other plans for them.",
      Language: 'Hindi',
      Country: 'India',
      Awards: 'N/A',
      Poster:
        'https://m.media-amazon.com/images/M/MV5BZTJiMjNjNzEtNjZkNS00YzA1LTk5MGQtODVhY2IxMDEwNTk1XkEyXkFqcGdeQXVyMTUzNTgzNzM0._V1_SX300.jpg',
      Ratings: [],
      Metascore: 'N/A',
      imdbRating: 'N/A',
      imdbVotes: 'N/A',
      imdbID: 'tt15576290',
      Type: 'movie',
      DVD: 'N/A',
      BoxOffice: 'N/A',
      Production: 'N/A',
      Website: 'N/A',
      Response: 'True',
    },
  ],
};
